### ISSUE TITLE
Should `extract_adaptor` API return `None` instead of `False`?

### ISSUE THREAD

**Issue by siv2r** [ZhePang/Python_Specification_for_Schnorr_Adaptor#15]
The `extract_adaptor` API returns `False` when it’s unable to generate a valid adaptor point. In one of our calls, we decided on using `False` because `None` is used to represent an infinity point. 

Wouldn’t it be more pragmatic to use `None` instead?

Here are my reasons:

- `extract_adaptor` is supposed to return a point, so returning a boolean value seems unusual
- The adaptor can never be an infinite point. At least, our APIs don’t support it, so reserving the `None` keyword doesn’t make sense.
    - Let’s say the user encodes the infinity adaptor point as `0x0000...0000` (33-byte array) and tries to create a pre-signature for it. This won't work because `cpoint(adaptor)` would raise value error. So, the adaptor can never be an infinity point in our APIs.
    - This also implies that the secadatpor can never be 0. Maybe we can add an `assert` for this in `extract_secadaptor`
    - If we really want to support signing with an infinity adaptor point, we can use [cpoint_ext](https://github.com/bitcoin/bips/blob/master/bip-0327/reference.py#L166) instead of `cpoint`
- BIP340 also follows this `None` approach. The `lift_x` function returns `None` when it cannot generate a valid point. Even though `None` represents the infinity point for the `point_add`, `point_mul`, and `point_negate` functions.

**Comment by jonasnick** [comment]
Agree that the return type should be `Optional[PlainPk]`. Since `None` is not not a plain public key, I don't see how a user could confuse this.

I think the function returns False now because it used to return `Point` at some point in the past and not `PlainPk`.
